<?php

namespace App\Entity;

abstract class PHPRCFunction
{
    protected 
        $name,
        $path,
        $comment,
        $output
    ;
    
    public function __construct(string $name, string $path, string $comment = null)
    {
        $this->name = $name;
        $this->path = $path;
        $this->comment = $comment ?? "FUNCTION GENERATED BY PHPRC";
        $this->output = $this->generate();
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * @return string
     */
    public function getComment(): string
    {
        return $this->comment;
    }

    /**
     * @return string
     */
    public function getOutput(): string
    {
        return $this->output;
    }
    
    abstract function generate():string;
}